repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-shebang-scripts-are-executable
      - id: check-case-conflict
      - id: check-ast
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-vcs-permalinks
      - id: mixed-line-ending

  - repo: https://github.com/hadialqattan/pycln # removes unused imports
    rev: 14197bfec1f357a9dc6b0c82a434a8f4c29de4b7 # frozen: v2.5.0
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: 1683a63d850e065495c05b771e4a20db010a58e7 # frozen: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0b19ef1fd6ad680ed7752d6daba883ce1265a6de # frozen: v0.12.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 38980559e3a605691d6579f96222c30778e5a69e # frozen: 3.0.0
    hooks:
      - id: forbid-binary
      - id: git-check

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: b2537099e1c0c5d734c7ab542697bacdd65c499d # frozen: 0.7.19
    hooks:
      - id: uv-lock
      - id: uv-export

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 77a9b532a32777d71fe24bdd9df8774ca92f9fac # frozen: v9.30.1
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
